sudo: required
services:
  - docker


before_install:
  - docker build -t rhadw/learn -f Dockerfile.dev .
script:
  - docker run rhadw/learn npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn"
  env: "Learn-env"
  bucket_name: "elasticbeanstalk-us-east-2-101061363974"
  bucket_path: "learn"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
